---
#
# App onboarding w/ Jenkins
#
- include_role:
    name: demo-monaco-gitops

#
# Merlin
#
- set_fact:
    use_case_ext_src_2: "https://{{ extra_vars.githubuser }}:{{ extra_vars.githubtoken }}@github.com/dynatrace-ace/ace-box-ext-merlin.git"
    use_case_ext_name_2: "ace-box-ext-merlin"
    use_case_ext_version_2: "feature/dashboard"

- name: Clone external use case
  ansible.builtin.git:
    repo: "{{ use_case_ext_src_2 }}"
    version: "{{ use_case_ext_version_2 }}"
    dest: "/tmp/{{ use_case_ext_name_2 }}"

- name: Synchronize Use Case role
  synchronize:
    src: "/tmp/{{ use_case_ext_name_2 }}/roles/{{ use_case_ext_default_name }}/"
    dest: "/home/{{ ace_box_user }}/ansible/roles/{{ use_case_ext_name_2 }}/"

- name: Synchronize roles
  synchronize:
    src: "/tmp/{{ use_case_ext_name_2 }}/roles/"
    dest: "/home/{{ ace_box_user }}/ansible/roles/"
    rsync_opts:
      - "--exclude={{ use_case_ext_default_name }}"

- name: Synchronize var override
  synchronize:
    src: "/tmp/{{ use_case_ext_name_2 }}/ace-ext.config.yml"
    dest: "/home/{{ ace_box_user }}/ansible/{{ use_case_ext_name_2 }}.config.yml"
  ignore_errors: True

- name: Source var override
  include_vars: "/home/{{ ace_box_user }}/ansible/{{ use_case_ext_name_2 }}.config.yml"
  ignore_errors: True

- include_role:
    name: "{{ use_case_ext_name_2 }}"
